services:
  api:
    build: .
    container_name: temp_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - app/database/.env

  postgres:
    image: postgres:15
    container_name: temp_postgres
    restart: always
    env_file:
      - app/database/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
